name: Build and Release

on:
  push:
    branches:
      - "*"
    tags:
      - "v*" # Triggers a formal release when you push a tag like v1.0
  pull_request:
    branches:
      - "*"
  workflow_dispatch: # Allows you to click "Run Workflow" manually

permissions:
  contents: write # Essential permission to create Releases

jobs:
  build:
    name: Build binaries
    runs-on: windows-2022
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:PlatformTarget=x86 build/t6-gsc-utils.sln

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}}-binaries
          path: build/bin/${{matrix.configuration}}/t6-gsc-utils.dll

  publish:
    name: Publish GitHub Release
    needs: build
    runs-on: ubuntu-latest
    # Run only on tags or manual triggers
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release-binaries/t6-gsc-utils.dll
            Debug-binaries/t6-gsc-utils.dll
          tag_name: ${{ github.ref_name }}
          name: Build ${{ github.ref_name }}
          draft: false
          prerelease: false
